## Assignment 5 N_Defranceschi

In [2]:
import numpy as np

In [34]:
Resistance_names = np.array(["Rin","Rwood_a","Rfiber","Rglass_fib","Rwood_b","Rgypsum","Rout"])
Resistance_types = np.array(["conv","cond","cond","cond","cond","cond","conv"])
Resistance_wood = np.array([0.12,0.14,0.23,0,0.63,0.079,0.03])
Resistance_insulation = np.array([0.12,0.14,0.23,0.7,0,0.079,0.03])
MaterialThickness = np.array([0,13,13,90,90,13,0])
MaterialStandardThickness = np.array([0,13,13,25,90,13,0])



In [56]:
Resistance_RValues_wood = np.zeros(7)
Resistance_RValues_wood

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [57]:
Resistance_wood[Resistance_types == "conv"]

array([ 0.12,  0.03])

In [58]:
Resistance_wood[Resistance_types == "cond"]*MaterialThickness[Resistance_types == "cond"]/MaterialStandardThickness[Resistance_types == "cond"]

array([ 0.14 ,  0.23 ,  0.   ,  0.63 ,  0.079])

In [59]:
Resistance_RValues_wood[Resistance_types == "conv"]=Resistance_wood[Resistance_types == "conv"]
Resistance_RValues_wood[Resistance_types == "cond"]=Resistance_wood[Resistance_types == "cond"]*MaterialThickness[Resistance_types == "cond"]/MaterialStandardThickness[Resistance_types == "cond"]
Resistance_RValues_wood

array([ 0.12 ,  0.14 ,  0.23 ,  0.   ,  0.63 ,  0.079,  0.03 ])

In [60]:
Resistance_RValuesWoodtot = Resistance_RValues_wood.sum()
Resistance_RValuesWoodtot
round(Resistance_RValuesWoodtot,3)

1.229

In [61]:
Resistance_RValues_insulation = np.zeros(7)
Resistance_RValues_insulation

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [48]:
Resistance_insulation[Resistance_types == "conv"]


array([ 0.12,  0.03])

In [49]:
Resistance_insulation[Resistance_types == "cond"]*MaterialThickness[Resistance_types == "cond"]/MaterialStandardThickness[Resistance_types == "cond"]

array([ 0.14 ,  0.23 ,  2.52 ,  0.   ,  0.079])

In [62]:
Resistance_RValues_insulation[Resistance_types == "conv"]=Resistance_insulation[Resistance_types == "conv"]
Resistance_RValues_insulation[Resistance_types == "cond"]=Resistance_insulation[Resistance_types == "cond"]*MaterialThickness[Resistance_types == "cond"]/MaterialStandardThickness[Resistance_types == "cond"]
Resistance_RValues_insulation

array([ 0.12 ,  0.14 ,  0.23 ,  2.52 ,  0.   ,  0.079,  0.03 ])

In [63]:
Resistance_RValuesInsulationtot = Resistance_RValues_insulation.sum()
Resistance_RValuesInsulationtot
round(Resistance_RValuesInsulationtot,3)

3.119

Computation of **deltaT**,**U** and **Q**

In [74]:
p = 50 
h = 2.5
A = p*h*(0.8)
U_wood = 1/Resistance_RValuesWoodtot
U_ins = 1/Resistance_RValuesInsulationtot
print(U_wood)
print(U_ins)


0.813669650122
0.320615581917


In [75]:
U_tot = 0.75*U_ins + 0.25*U_wood
print("The overall thermal coefficient")
U_tot
round(U_tot,4)

The overall thermal coefficient


0.4439

In [76]:
T_inside = 22
T_outside = -2
deltaT = T_inside - T_outside
print("The temperature difference")
deltaT

The temperature difference


24

In [77]:
Q = U_tot*deltaT*A
print("The rate of heat transfer")
Q


The rate of heat transfer


1065.3098375243364